name: Contexts Demo

on: workflow_dispatch

env:
  GLOBAL_ENV: 'Hello from global env'

jobs:
  show-github:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context
        run: |
          echo 'Repository: ${{ github.repository }}'
          echo 'Branch/Ref: ${{ github.ref }}'
          echo 'Commit SHA: ${{ github.sha }}'
          echo 'Actor: ${{ github.actor }}'
          echo 'Event: ${{ github.event_name }}'

  show-env:
    runs-on: ubuntu-latest
    steps:
      - name: Show env context
        run: |
          echo 'Global ENV: ${{ env.GLOBAL_ENV }}'
          echo "PATH: $PATH"

  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret exists
        run: |
          if [ -n '${{ secrets.MY_SECRET }}' ]; then
            echo 'Secret is set (not showing value)'
          else
            echo 'Secret is NOT set'
          fi

  show-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: Print matrix value
        run: |
